#include <stdio.h>
#include <time.h>

#include "lex.h"
#include "parse.h"
#include "shared.h"

const char *input_name = "<stdin>";

int
main(int argc, char **argv)
{
        char date[64];
        time_t now = time(NULL);
        int status;

        if (argc > 2) {
                fprintf(stderr, "Usage: %s [file]\n", argv[0]);
                return 1;
        }

        yyin = stdin;
        yyout = stdout;
        if (argc == 2) yyin = fopen(input_name = argv[1], "r");
        if (yyin == NULL) {
                perror(input_name);
                return 1;
        }

        strftime(date, sizeof date, "%a, %d %b %Y %H:%M:%S %z", localtime(&now));
        printf("// Generated by %s %d.%d.%d on %s\n", argv[0], VMAJ, VMIN, VPAT, date);
        printf("#define MALPP %d\n", VMAJ * 10000 + VMIN * 100 + VPAT);
        printf("#include <optional>\n");
        printf("#include \"malleable.hpp\"\n");
        printf("\n");

        status = yyparse();

        printf("\n");
        printf("#undef MALPP\n");

        if (argc == 2) fclose(yyin);
        return status;
}
